// Re-exported from the @spacebiz/ui library package
export {
  GAME_WIDTH,
  GAME_HEIGHT,
  MAX_CONTENT_WIDTH,
  SIDEBAR_WIDTH,
  CONTENT_GAP,
  HUD_TOP_BAR_HEIGHT,
  HUD_BOTTOM_BAR_HEIGHT,
  NAV_SIDEBAR_WIDTH,
  CONTENT_TOP,
  CONTENT_HEIGHT,
  CONTENT_LEFT,
  SIDEBAR_LEFT,
  MAIN_CONTENT_LEFT,
  MAIN_CONTENT_WIDTH,
  FULL_CONTENT_LEFT,
  FULL_CONTENT_WIDTH,
} from "@spacebiz/ui";
