import { test, expect } from "./fixtures/sft.ts";
import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Tier-2 smoke spec — verifies the IP-bearing rogue-universe-shared subsystems
 * (CEO portraits, galactic news ticker, adviser panel, empire borders, ship
 * map sprites) render correctly in the live game after the unit-15 migration.
 *
 * NOTE: As of writing, unit 15 has not landed and tier-2 sources still live
 * under `src/ui/`. The spec deliberately does not import from those paths —
 * it drives the live game via `__sft` and asserts on observable runtime
 * state, so it works against either source location.
 */

const SHOTS_DIR = path.join(process.cwd(), "e2e", "screenshots", "tier2");
const SEED = 0xa11ce; // deterministic seed for this spec

function ensureShotsDir(): void {
  if (!fs.existsSync(SHOTS_DIR)) fs.mkdirSync(SHOTS_DIR, { recursive: true });
}

/** True when at least one ship-map texture key has been generated. */
async function shipMapTexturesExist(
  page: import("@playwright/test").Page,
): Promise<boolean> {
  return page.evaluate(() => {
    // Phaser's TextureManager is global per Game instance; probe with the
    // canonical keys generated by generateShipMapSprites at boot.
    const tex = window.__SFT_GAME?.textures;
    if (!tex) return false;
    return ["ship-map-cargoShuttle", "ship-map-fastCourier"].some((k) =>
      tex.exists(k),
    );
  });
}

test.describe("Tier 2 smoke", () => {
  test.beforeAll(() => ensureShotsDir());

  test("portraits, news, adviser, and map subsystems render after newGame", async ({
    page,
    sft,
  }) => {
    // 1. Boot main game (handled by the sft fixture page.goto("/")).
    await sft.ready();

    // 2. Start a new game with a deterministic seed.
    await sft.seed(SEED);
    await sft.actions.newGame(SEED);
    await sft.readyWithWidgets();

    // Some narrative wiring fires after a short delay (ADVISER_ONBOARD_DELAY_MS);
    // give the boot sequence a tick to settle before sampling state.
    await page.waitForTimeout(800);

    // 3. CEO portrait — verify the player's CEO portrait texture is loaded.
    await expect
      .poll(async () => (await sft.getPortrait()).loaded, { timeout: 8000 })
      .toBe(true);

    const portrait = await sft.getPortrait();
    expect(portrait.ceoId).toBeTruthy();
    expect(portrait.textureKey).toMatch(/^portrait-/);
    expect(portrait.isPlayer).toBe(true);

    await page.screenshot({
      path: path.join(SHOTS_DIR, "01-ceo-portrait.png"),
      fullPage: false,
    });

    // 4. News ticker — generateTickerFeed needs a TurnResult to pull from.
    // Rather than drive the slow end-turn → SimPlaybackScene → TurnReport
    // flow (which can be blocked by a confirmation modal at game start),
    // seed a synthetic TurnResult via the test-only `_seedFakeTurnResult`
    // hook. This verifies the live `__sft.getNewsItems()` pipeline including
    // generateTickerFeed's leader/stock/flavor mixers.
    await page.evaluate(() => window.__sft!._seedFakeTurnResult());

    const items = await sft.getNewsItems();
    expect(items.length).toBeGreaterThan(0);
    for (const item of items.slice(0, 3)) {
      expect(typeof item.text).toBe("string");
      expect(item.text.length).toBeGreaterThan(0);
      expect(typeof item.category).toBe("string");
    }

    await page.screenshot({
      path: path.join(SHOTS_DIR, "02-news-ticker.png"),
      fullPage: false,
    });

    // 5. Adviser — open EmpireScene (which renders a portrait panel) and
    // verify adviser state is queryable. The adviser panel itself lives in
    // GameHUDScene; verify pendingMessages is an array (may be empty) and
    // the snapshot wrapper shape is intact.
    await sft.actions.openScene("EmpireScene");
    await page.waitForTimeout(500);

    const adviser = await sft.getAdviserState();
    expect(adviser).toHaveProperty("state");
    expect(adviser).toHaveProperty("pending");
    expect(Array.isArray(adviser.state.pendingMessages)).toBe(true);
    expect(adviser.pending).toBe(adviser.state.pendingMessages.length);

    await page.screenshot({
      path: path.join(SHOTS_DIR, "03-empire-adviser.png"),
      fullPage: false,
    });

    // 6. Map subsystems — RoutesScene mounts the MiniMap (which uses
    // EmpireBorders + ShipMapSprites textures). Open it and verify it
    // mounts widgets without throwing.
    await sft.actions.openScene("RoutesScene");
    await sft.readyWithWidgets();

    const routesWidgets = await sft.list();
    expect(routesWidgets.length).toBeGreaterThan(0);
    expect(routesWidgets.some((w) => w.scene === "RoutesScene")).toBe(true);

    // ShipMapSprites textures are generated procedurally at boot; assert at
    // least one of the canonical keys exists in Phaser's TextureManager.
    expect(await shipMapTexturesExist(page)).toBe(true);

    await page.screenshot({
      path: path.join(SHOTS_DIR, "04-routes-minimap.png"),
      fullPage: false,
    });

    // Final invariant sweep — no recorded violations means no scene crashed.
    const violations = await sft.invariantViolations();
    expect(violations).toEqual([]);
  });
});
