import type { FlavorTemplate, TickerCategory } from "./types.ts";
import { FLAVOR_CATEGORIES } from "./categories.ts";

/**
 * Galactic News flavor templates. ~500 entries across 20 categories, ~25 each.
 *
 * Tone notes:
 *   • Serious-corporate categories (politics, corporate, market_mover, science,
 *     cosmic_weather) read like real wire copy.
 *   • Light/satirical categories (sports, celebrity, fashion, food, blotter,
 *     local) lean into dry observation.
 *   • Sci-Fi Homages are clear genre nods (Hitchhiker's, Asimov, Dune, Star Trek,
 *     Blade Runner, Star Wars, Firefly, Alien). Reader-in-on-the-joke voice.
 *
 * Tokens documented in `tokens.ts`.
 */

// ── 1. Galactic Politics ───────────────────────────────────────
const POLITICS: string[] = [
  "{empire} parliament adjourns over tariff vote, third recess this cycle",
  "Trade summit between {empire} and {empire2} ends in 'productive ambiguity'",
  "{empire} ambassador denies treaty leak, denies leak occurred at all",
  "Sector {sector} council votes {n2}-{n} to formally ignore the news",
  "{empire} unveils {n}-point plan to deal with {empire2}; six points classified",
  "Border lane {planet}-{planet2} closed for 'review of paperwork integrity'",
  "{empire} prime minister survives no-confidence vote by {n} votes",
  "Diplomatic pouch from {empire2} returns unopened, still smoking",
  "Mediator declares peace talks 'on a brisk simmer' as week three opens",
  "{empire} coalition wobbles after coalition partner declares it 'fine'",
  "Election monitors clear {empire} ballot; turnout reported at {percent}%",
  "Tariff exemption granted to {commodity} importers after lobbying surge",
  "{empire} senate hearing on AI rights extends into a {n2}th day",
  "Diplomatic scandal: {ceo} caught quoting {empire2} press in {empire} brief",
  "{empire} unveils new flag; designer cites 'fewer hostile angles'",
  "Treaty of {planet} hits article {n2}; lawyers expect 'modest fallout'",
  "Sector audit finds {empire} ministry has been quietly out of pencils for months",
  "{empire} foreign minister cancels trip after passport spelled wrong",
  "Constitutional court rules {commodity} not technically a vegetable",
  "{empire} press secretary clarifies that 'absolutely not' was a tonal choice",
  "{ceo} appointed special envoy to {empire2}; tickets one-way",
  "Public referendum on naming new sector ends with 'Sector McSectorface' barred",
  "{empire} introduces tariff on hope; economists relieved it is enforceable",
  "Joint communique describes ongoing crisis as 'opportunity-shaped'",
  "Census of {empire} citizens completed; results pending appeal by {empire2}",
];

// ── 2. Corporate Earnings ──────────────────────────────────────
const CORPORATE: string[] = [
  "{company} posts {percent}% revenue growth on strong {commodity} demand",
  "{company} narrows quarterly loss; CEO {ceo} cites 'disciplined optimism'",
  "{company} announces hostile bid for rival; rival announces stronger coffee",
  "Board reshuffle at {company}; three directors departing for 'health reasons'",
  "{company} reports record {commodity} throughput across {sector} routes",
  "Shareholders approve {company} buyback worth {credits}",
  "{company} delays earnings call citing 'unforeseen but spreadsheet-shaped issue'",
  "{company} CFO replaced after Q2 surprise; replacement also surprised",
  "{ceo}'s compensation package draws fire; {ceo} draws fire elsewhere",
  "{company} merger with {company} hits regulator wall in {empire}",
  "{company} pays {credits} fine for 'aggressive but technically legal scheduling'",
  "{company} guidance raised; analysts raise eyebrows in synchrony",
  "{company} writes down {credits} of {commodity} inventory after market rotation",
  "Dividend held flat at {company}; investors held breath, then exhaled politely",
  "{company} carbon-trade desk closes after carbon refuses to cooperate",
  "{company} restructures middle management; middle management restructures résumés",
  "{company} introduces 'value tier' service; tier ends three meters short of orbit",
  "Activist investor builds {percent}% stake in {company}, vows 'gentle fury'",
  "{company} confirms layoffs at {planet} division; severance offered in {commodity}",
  "{company} chair {ceo} steps down 'to spend more time with portfolio'",
  "Whistleblower at {company} alleges accounting performed 'inventively'",
  "{company} opens new HQ on {planet}; chairs alone cost {credits}",
  "{company} pulls full-year guidance; partial guidance confined to lobby",
  "{company} announces {commodity} subscription service; cancellation requires lawyer",
  "Audit committee at {company} completes review; review now under review",
];

// ── 3. Market Movers ───────────────────────────────────────────
const MARKET_MOVER: string[] = [
  "{stock} jumps {percent}% on {commodity} contract win",
  "{stock} slides {percent}% after disappointing {commodity} guidance",
  "Volume surges in {stock}; {percent}% above twelve-cycle average",
  "Analysts at {empire} bank double-upgrade {stock}, citing 'general vibe'",
  "{stock} hits new {n2}-cycle high amid sector rotation into transport",
  "Short interest in {stock} climbs to {percent}% of float",
  "Hedge fund {ceo Fund} reveals {percent}% position in {stock}",
  "{stock} falls below moving average; chartists murmur ominously",
  "Index of {sector} freight haulers gains {percent}% week-on-week",
  "{commodity} futures spike on {planet} mine outage",
  "Spread between {commodity} and {commodity} narrows to multi-cycle low",
  "{stock} dual-listed on {empire} exchange after compliance review",
  "Insider sale of {credits} in {stock} disclosed by chief operations officer",
  "{stock} suspended for {n} hours pending material announcement",
  "Bond yields on {empire} sovereigns tick up {percent} basis points",
  "{stock} dividend cut to zero; CEO {ceo} cites 'temporal cashflow'",
  "Margin call cascade hits {stock} after {commodity} flash crash",
  "Initial public offering of {company} priced at upper band, raises {credits}",
  "Activist letter sends {stock} up {percent}% in pre-market trading",
  "Quant strategy 'Boltzmann-7' allegedly drove {percent}% of {stock} volume",
  "Gold-pressed latinum benchmark steady; nobody asks why it still exists",
  "Dark pools see record activity in {stock} ahead of merger vote",
  "{stock} added to {empire} sector index, replacing bankrupt {company}",
  "Volatility index across {sector} freight names climbs to multi-cycle high",
  "{stock} closes flat after intraday {percent}% swing 'on no news whatsoever'",
];

// ── 4. Crime & Piracy ──────────────────────────────────────────
const CRIME: string[] = [
  "Customs seize {tonnage} of contraband {commodity} near {port}",
  "Pirate raid on {planet} convoy nets {credits}, two {adj} captives",
  "{empire} fleet patrol disrupts smuggling ring in {sector}",
  "Bounty hunter guild posts {credits} reward for {ceo} after warrant issued",
  "{port} authorities arrest {n2} in dawn raid on counterfeit {commodity} ring",
  "Heist at {company} vault on {planet}; escape vehicle 'borrowed' from staff",
  "Pirate broadcast jams {sector} freight lanes for {n} cycles",
  "{empire} coast guard intercepts {tonnage} of restricted {commodity}",
  "Mob trial on {planet} ends in mistrial; jury reportedly relieved",
  "Insurance fraud at {company} estimated at {credits}; perpetrator clumsy",
  "Customs robot rebooted three times during {port} contraband sweep",
  "Cyber-heist drains {credits} from {company} treasury via 'helpful' chatbot",
  "Black-market {commodity} prices double on {planet} after sting operation",
  "{ceo} questioned over {commodity} kickback scheme, declines coffee politely",
  "Drug ring on {planet} bust nets {tonnage} of synthetic euphoriants",
  "{empire} marshals raid {planet} cantina; cantina found largely cantina-shaped",
  "Pirate king of {sector} declares amnesty week, accepts {commodity} in tribute",
  "Heirloom {commodity} smuggled past {port} scan in fake {commodity} crate",
  "Bounty filed against captain of vessel last seen 'departing rapidly'",
  "{empire} ministry confirms {n} indictments in {company} bribery probe",
  "Forged customs stamps from {planet} traced to ex-{empire} bureaucrat",
  "Catastrophic insurance claim filed by {company} after 'mysterious' fire",
  "Asteroid prospector arrested for filing claim on a moon",
  "{port} police recover {credits} of stolen art, none of it requested back",
  "Three indicted in {empire} pension fund skim; total losses {credits}",
];

// ── 5. Science & Tech ──────────────────────────────────────────
const SCIENCE: string[] = [
  "{empire} researchers claim FTL coil efficiency record, peer review pending",
  "{company} R&D unveils new fusion bottle; bottle still bottle-shaped",
  "Quantum tunneling breakthrough at {planet} institute reduces ping by {percent}%",
  "Terraforming progress on {planet} reaches stage {n}, atmosphere now breathable-ish",
  "{empire} funds antimatter containment study; classified, then unclassified, then reclassified",
  "Robotics team on {planet} demonstrates self-replicating drone swarm — controllably",
  "Cold fusion trial at {empire} lab produces heat, light, and a moderate fire",
  "Subspace relay network expanded across {sector}, latency down {percent}%",
  "{empire} bioethics panel debates uplift of {adj} cephalopods",
  "Deep-space probe {n} returns data after {n2}-year transit; mostly static",
  "Algorithm at {company} trims fuel use {percent}% by 'firmly suggesting' shorter routes",
  "{empire} unveils nanofabric armor; weighs {tonnage}, defeating original purpose",
  "Solar sail trial at {system} reaches half-c, then politely turns back",
  "{empire} confirms quantum computer factored {n}-digit prime ahead of schedule",
  "AI alignment workshop at {planet} concludes, AI takes minutes",
  "Cryostasis trial revives {n2} volunteers; {n} report mild dreaming",
  "{company} patents fold-space corridor; lawyers fold space, then unfold it",
  "Genome of {planet} fungus published; {percent}% overlap with {empire2} cuisine",
  "Plasma engine test on {planet} produces {percent}% efficiency gain, {n} singed eyebrows",
  "Researchers at {empire} confirm dark matter exists, definitely, this time",
  "{empire} space telescope sees back to first {n2} million years; calls it dim",
  "{company} R&D reveals room-temperature superconductor, shipping room not included",
  "Holographic compression standard adopted by {sector} after {n}-year fight",
  "Gravity wave observatory on {planet} reports background hum 'too cheerful'",
  "{empire} releases open-source jump drive plans; lawyers also open-sourced",
];

// ── 6. Sports ──────────────────────────────────────────────────
const SPORTS: string[] = [
  "{empire} routs {empire2} 18-3 in zero-G ball semifinal",
  "Asteroid racing championship returns to {sector} after {n}-cycle suspension",
  "{empire} gravball star {ceo} signs record contract with {empire2} club",
  "{planet} stadium expansion approved; capacity now {n2},000",
  "Underdog squad from {planet} upsets reigning {empire} champions",
  "Doping scandal rocks {sector} league after {commodity} traces found",
  "Esports tourney on {planet} draws {n2} million viewers, three lawsuits",
  "{empire} league cancels mid-season after sponsor goes bankrupt",
  "Coach {ceo} fired despite winning record; cites 'creative differences with cosmos'",
  "Vacuum-fencing makes Olympic provisional list after {n} cycles of lobbying",
  "{empire} fans riot after referee call; referee files for hazard pay",
  "Robot wrestling league suspends {n} bots for unsportsmanlike conduct",
  "{planet} hosts inaugural microgravity marathon; finish line currently in orbit",
  "{empire} swimmer {ceo} breaks zero-g freestyle record by {percent}%",
  "Trade deadline brings {n2} player swaps across {sector} hockey league",
  "Athletics committee rules {commodity} energy drinks 'borderline acceptable'",
  "{empire} chess champion narrowly defeats AI again, claims 'felt different this time'",
  "Stadium pie thrower at {planet} match earns lifetime ban, {n}-cycle book deal",
  "Surfing league launches plasma division on {system}; safety waivers thicken",
  "{empire} squash federation merges with raquet federation, {empire2} unimpressed",
  "Boxing match on {planet} ends in draw after both fighters apologize",
  "Sled racing returns to {planet}; sleds, alarmingly, mostly self-driving",
  "{empire} fencing star {ceo} retires undefeated, with {n2} ribbons",
  "Drone derby on {planet} attracts crowds, three rogue drones still missing",
  "Goaltender {ceo} traded for two prospects and a shipment of {commodity}",
];

// ── 7. Celebrity & Media ───────────────────────────────────────
const CELEBRITY: string[] = [
  "Holovid star {ceo} denies third divorce in weekly statement",
  "Pop sensation {ceo} releases album recorded entirely in low orbit",
  "{ceo} spotted dining with rival {ceo2}; PR teams update talking points",
  "Reality show {n}-Body Problem renewed for fourth season on {empire} network",
  "{ceo} apologizes for comments about {empire2}; later apologizes for the apology",
  "{company} executive {ceo} appears on talk show, says nothing of note for {n} hours",
  "Director of 'Vacuum Heart' announces sequel; lead actor still missing in space",
  "{ceo}'s memoir tops bestseller list in {empire}; ghost-writer credited as 'mostly'",
  "Influencer feed on {planet} crashes after {n2} million simultaneous yawns",
  "Music streamer {company} pays artists {credits} after {n}-cycle dispute",
  "Galactic award show host {ceo} makes joke about {empire}, reservations cancelled",
  "Tabloid claims {ceo} cloned, {ceo} denies, both {ceo}s deny clone",
  "Documentary on {company} executives 'baroque, terrifying, also long'",
  "{empire} broadcaster bans song deemed 'subversively catchy'",
  "Magazine names {ceo} 'Most Reluctantly Respected' for third year",
  "Variety show on {planet} cancelled after {n} contestants vanish in week one",
  "{ceo} pet sentient kelp accepts honorary doctorate from {empire} university",
  "Streaming wars heat up: {company} debuts ad-tier 'with mild surveillance'",
  "{ceo} announces tour spanning {n2} planets; tour bus is also a yacht",
  "Late-night host roasts {empire} cabinet; cabinet roasts back via official channels",
  "{ceo} buys {company} just to fire one critic; analysts call it 'committed'",
  "Sequel to 'Halls of Vorga' delayed again; halls reportedly still being painted",
  "Reality couple {ceo} and {ceo2} renew vows on live broadcast, ratings flat",
  "{empire} broadcaster apologizes for typo that started a minor war",
  "Holographic concert on {planet} draws record crowd, {n} fainted from refractive joy",
];

// ── 8. Cosmic Weather ──────────────────────────────────────────
const COSMIC_WEATHER: string[] = [
  "Class-{n} ion storm forecast over {system} by next cycle",
  "Solar flare warning issued for {planet}; communications expected patchy",
  "{empire} weather service: gravitational tides {percent}% above normal in {sector}",
  "Comet ML-{n2} grazes {planet} orbit; observatory reports 'spectacular, mostly'",
  "Magnetic reversal predicted on {planet} within {n} cycles, compasses unhappy",
  "Cosmic ray surge expected to peak Tuesday across {sector} lanes",
  "{empire} space weather bureau issues navigational hazard for {system}",
  "Aurora forecast on {planet}: vivid, possibly haunting",
  "Subspace turbulence alert for jump corridor between {planet} and {planet2}",
  "Hypernova candidate identified {n2} parsecs out; arrival in {n2} millennia",
  "Asteroid swarm grazes {planet} atmosphere; {n} new craters logged",
  "Meteor shower expected over {planet} hemisphere, peak rate {n2}/hour",
  "Solar wind forecast: brisk, occasionally insolent",
  "Black hole merger detected in {sector}; tides briefly philosophical",
  "{empire} bureau confirms gravitational lensing event near {system}",
  "Cosmic background hum increased by {percent}% in {sector}, scientists puzzled",
  "Pulsar {n} timing drift detected; maintainers issue patch",
  "Coronal mass ejection grazes {planet}; auroras visible from sub-orbit",
  "Snow forecast on Olympus Domes, {planet}; {percent}% accumulation expected",
  "{empire} forecasts ten cycles of suspiciously perfect weather; emergency drills planned",
  "Tidal anomaly raises {port} sea level {percent}cm; insurers blink slowly",
  "Radio blackout expected across {sector} from solar disturbance",
  "Atmospheric pressure on {planet} drops {percent}%, residents 'feel it in knees'",
  "Brown dwarf flyby alters {system} orbits by {percent}%, calendars adjusted",
  "Eclipse on {planet} draws record tourism; vendors run out of {commodity}",
];

// ── 9. Local Planet News ───────────────────────────────────────
const LOCAL: string[] = [
  "{port} traffic council unveils new pedestrian sky-bridge",
  "{planet} mayor opens new transit hub two cycles late, three over budget",
  "Civic statue of {ceo} unveiled at {port}; pigeons unimpressed",
  "{port} farmer's market doubles in size; vendors triple in arguments",
  "{planet} water rationing lifted after {n} cycles of {commodity} importation",
  "New library opens in {port} downtown, named after a deceased benefactor",
  "{port} bus route 7 rerouted after sentient potholes refuse mediation",
  "{planet} school board approves new curriculum, parents tentatively pleased",
  "Elderly resident of {port} celebrates {n2}-cycle birthday, attributes longevity to spite",
  "Power outage on {port} block resolved after {n} hours, kettle saved",
  "{port} street fair this weekend; {commodity} festival expected to disappoint mildly",
  "{planet} hospital adds new wing dedicated to {empire} settlers",
  "Pothole repair on {port} main strip enters phase {n}; locals adjust commute",
  "Local pet on {planet} returns home after {n2} cycles missing, brings friends",
  "{port} council adopts new recycling bins; bins recycled from old recycling bins",
  "Volunteer cleanup at {planet} canal removes {tonnage} of debris, two oddities",
  "{port} elementary school wins regional debate trophy, brings home {commodity}",
  "Construction at {port} intersection enters {n2}th week, drivers philosophical",
  "{planet} farmer's almanac predicts pleasant cycle, ignores all evidence",
  "{port} community center reopens after fire; smell of {commodity} still mild",
  "Local sentient hedge wins {planet} garden contest by default",
  "{port} parade cancelled after lead float experiences existential lag",
  "{port} library hosts {commodity} sculpture exhibit, attendance moderate",
  "Mayor of {port} apologizes for jokes during ribbon cutting, ribbon survives",
  "{planet} weather predicts rain; rain predicts {planet} weather",
];

// ── 10. Health & Medical ───────────────────────────────────────
const HEALTH: string[] = [
  "Longevity clinic opens on {port}; package starts at {credits}",
  "{empire} health authority recalls {commodity} batch after {n2} reports of mild glow",
  "Vaccination drive in {sector} reaches {percent}% coverage milestone",
  "Hospital on {planet} pioneers neural repair; success rate now {percent}%",
  "Outbreak of {adj} fever on {planet} contained within {n} cycles",
  "{empire} medical board licenses uplift therapy for {commodity} workers",
  "Genetic counseling lines on {port} backlog now {n2} cycles deep",
  "Telemedicine network spans {sector}; latency reduces by {percent}%",
  "{company} pharma subsidiary recalls painkiller; replacement also being recalled",
  "Surgeons on {planet} debut zero-g spine repair; patient {percent}% taller",
  "Galactic flu season opens; {empire} clinics report shortage of {commodity}",
  "{empire} ban on cloning amended after lawyers cloned the previous ban",
  "Mental health awareness week in {sector}; productivity briefly drops {percent}%",
  "Dental implant breakthrough at {planet} institute; chewing efficiency up {percent}%",
  "Eye surgery on {planet} gives recipients {adj} vision, debate ongoing",
  "Herbal remedy on {port} found to be {percent}% placebo, {percent}% paint",
  "{empire} hospitals adopt AI triage; queue still long, just better-organized",
  "Birthrate on {planet} ticks up {percent}%; daycare waitlists explode",
  "Robotics-assisted surgery succeeds on {n2}th attempt at {planet} clinic",
  "Cosmic-radiation-induced rash sweeps {sector}; cure: more sun, less radiation",
  "{empire} surgeons graft sentient kelp into volunteer's spine; volunteer pleased",
  "Public health study finds {percent}% of {planet} residents have not slept properly",
  "{commodity} now classified as 'mostly therapeutic' by {empire} board",
  "Pediatric ward on {planet} opens new wing for {adj} aliens",
  "{port} pharmacist replaces label printer, errors drop {percent}%",
];

// ── 11. Religion & Philosophy ──────────────────────────────────
const RELIGION: string[] = [
  "Cult of the Frozen Logician schisms over heat-death debate",
  "{empire} interfaith council adds {n}th deity, removes one nobody worshipped",
  "Pilgrimage season on {planet} opens; capacity capped at {n2},000",
  "{empire} monastery on {planet} debates whether AI souls qualify for {commodity}",
  "Galactic ethics conference adjourns after {n} cycles, no decisions made",
  "Priest {ceo} excommunicated for selling indulgences denominated in {commodity}",
  "Order of the Slow Computation accepts new initiates on {port}",
  "{empire} census records {percent}% increase in 'spiritual but unaffiliated'",
  "Doomsday cult relocates predicted apocalypse to following Tuesday",
  "{empire} church of the Algorithm publishes update {n}.{n2}, schism imminent",
  "Theology student on {planet} proves God's existence in {n} steps, last step shaky",
  "{empire} shrine to {commodity} reopens after restoration, smell stronger than ever",
  "{port} ethical philosophy department shrinks {percent}%, students unrepentant",
  "Clergy on {planet} debate whether bots can take confession; bots noncommittal",
  "Annual fast on {planet} ends with feast that breaks last cycle's record",
  "{empire} druids release white paper on photosynthetic prayer techniques",
  "{port} church bells tolling out of sync; congregation oddly united",
  "Order of the Empty Beaker celebrates founding {n2}-cycle ago, glasses raised dryly",
  "Book of Predictions translated; predictions remain unfailingly vague",
  "{empire} imam delivers sermon on {commodity} ethics, audience nods politely",
  "Cult on {planet} adopts new symbol; symbol coincidentally trademarked",
  "Theological journal on {port} publishes paper titled 'Maybe?', cited {n2} times",
  "{empire} parliament debates separating {commodity} subsidy from religious tax",
  "Trappist colony on {planet} releases brewing log, surprisingly racy",
  "Ascetic order on {port} divests of all material possessions, except {commodity}",
];

// ── 12. Odd Crime Blotter ──────────────────────────────────────
const BLOTTER: string[] = [
  "{port} man arrested attempting to mail self to {planet}",
  "Resident of {port} tries to pay parking fine in {commodity}, arrested politely",
  "Two on {planet} cited for racing rental loaders down a service tube",
  "{port} business reports break-in; intruder left {credits} cash by accident",
  "Burglar on {planet} fell asleep mid-heist, woke to coffee and {empire} police",
  "{port} officials warn against feeding {adj} sentient pigeons synthetic bread",
  "Driver on {planet} cited for {percent}% over speed limit in school zone",
  "Stolen {commodity} returned to {port} shop with apology note and gift card",
  "Suspect on {planet} disguised as council statue evaded capture for {n} cycles",
  "{port} police: 'No, the alien did not eat your homework, please stop calling'",
  "Bicycle theft ring on {planet} rolled up after suspect rode to station",
  "{port} cashier subdues robber with sandwich; sandwich survives",
  "Two cited for performing impromptu opera in {planet} restricted airspace",
  "{port} woman files report against own past self, case closed",
  "Loiterer outside {planet} bakery turns out to be undercover food critic",
  "Resident of {port} accidentally adopts riot bot, names it 'Spunky'",
  "{port} police remind public: drone delivery services are not a taxi for cats",
  "{planet} man arrested for selling moon, claims he meant a different moon",
  "Pickpocket on {planet} returns wallet with detailed financial advice",
  "{port} police chase suspect at jogging speed for {n2} blocks, suspect tires first",
  "Suspect attempts escape via shopping cart, achieves moderate velocity",
  "{port} residents report 'dignified looking thief' wearing top hat at robbery",
  "{port} bakery robbed of pastries; suspect described as 'crumbly'",
  "Driver on {planet} ticketed for U-turn through wedding procession",
  "{port} parking dispute settled by {n}-round dance-off, both fined",
];

// ── 13. Food & Cuisine ─────────────────────────────────────────
const FOOD: string[] = [
  "Three-star reviewer pans {port} restaurant: 'tastes of regret'",
  "{planet} chef {ceo} wins regional cup with synthetic {commodity} dish",
  "{port} food festival sells out of {commodity} skewers in {n} hours",
  "{empire} diet trend: cut all carbs, add more {commodity}, drink more water",
  "Restaurant on {planet} closes after {n2} cycles; landlord raises rent {percent}%",
  "{ceo}'s new cookbook 'How to Boil Water in Vacuum' enters bestseller list",
  "{port} health inspector closes {n} kitchens, cites 'enthusiastic ingredients'",
  "Galactic fast food chain {company} debuts {commodity} burger, supply chain creaks",
  "{planet} oyster bar reopens after {commodity} shortage; oysters relieved",
  "Chocolate alternatives gain ground in {empire}; cocoa lobby threatens {n} things",
  "Critic visits {port} taqueria, leaves reviewing it as 'a place to be'",
  "{empire} bans synthetic {commodity} cheese in pizza, pizzeria community shrugs",
  "Tasting menu at {planet} restaurant includes {n} courses, {n} apologies",
  "{port} brewery wins prize for ale aged in vacuum, tastes 'mostly like ale'",
  "Vegan butcher opens on {planet}; recipe inspires deep philosophical questions",
  "{empire} food truck on {port} draws {n2} block line, queue creates own micro-economy",
  "Recipe for grandma's {commodity} stew leaks online, grandma issues press release",
  "{port} fine dining scene now requires reservation, ID, blood type, and patience",
  "Regional dish from {planet} declared 'tolerable' by visiting {empire} delegation",
  "Coffee shop on {port} introduces {n}-shot espresso, requires waiver",
  "{ceo}'s pop-up dinner sells out in {n} minutes; tickets resold for {credits}",
  "{empire} bans imitation {commodity} from being labelled real {commodity}",
  "{port} bakery drops bagel from menu; protests escalate to {n2} signatures",
  "{empire} cuisine wins galactic award for 'least frightening texture'",
  "Chef on {planet} accidentally invents new spice; bottles flying off shelves",
];

// ── 14. Real Estate & Megastructures ───────────────────────────
const REALESTATE: string[] = [
  "Megastructure permit issued for orbital ring above {planet}",
  "{port} luxury tower announces residency at {credits} per unit",
  "Asteroid claim on {planet} system goes for record {credits}",
  "{empire} approves construction of {n}-tier arcology on {planet}",
  "{port} home prices climb {percent}% year-over-year, buyers apoplectic",
  "Hyperloop hub at {port} clears final permits; objections filed in triplicate",
  "Vacant {company} office on {planet} sells for {credits}, smells faintly of decisions",
  "Skybridge connecting {port} towers wins design award, fails inspection",
  "{empire} announces new spaceport on {planet}; existing spaceport offended",
  "Co-living scheme on {port} promises {percent}% lower rent, {percent}% more drama",
  "Listing on {port} described as 'cozy'; cozy means structural concerns",
  "{empire} zoning board approves vertical farm overlooking {port} downtown",
  "Repossessed orbital habitat sold at auction for {credits}",
  "{port} building boom pushes hardhat shortage into {n}th cycle",
  "Land developer {ceo} unveils 'eco-friendly' moonbase featuring lawns",
  "{empire} new town charter approves naming rights to {company}",
  "Condo board on {planet} bans noise, joy, hover-pets in single 4 a.m. vote",
  "Skyscraper on {port} fails wind test in vacuum, engineers nod knowingly",
  "{empire} luxury resort breaks ground on {planet}; ground breaks back",
  "{port} mall reopens with new {commodity} kiosks; security buys earplugs",
  "Tycoon {ceo} buys entire moon, says 'collateral'",
  "{empire} reveals {n}-cycle plan to convert asteroid belt to housing",
  "Renters association on {port} formed; first vote, by {n2} margin, demanded snacks",
  "Estate sale on {planet} clears {credits} of antique {commodity}",
  "Penthouse on {port} listed for {credits}, includes {n} ghosts at no extra charge",
];

// ── 15. Travel & Tourism ───────────────────────────────────────
const TRAVEL: string[] = [
  "{planet} resort posts record {percent}% occupancy this cycle",
  "Cruise liner Voidsong delayed {n} cycles after engine 'sneezed'",
  "{empire} tourism ministry launches campaign: 'visit {planet}, eventually'",
  "Backpacker route through {sector} draws {percent}% more travelers year-on-year",
  "{port} spaceport adds direct service to {planet}, three layovers eliminated",
  "Adventure tourism on {planet} now requires {n}-cycle waiver",
  "{empire} hotel chain {company} adds {n2} properties this cycle",
  "Glamping on {planet} canyon rim wins galactic 'serenity, mostly' award",
  "{ceo}'s travel show debuts; first episode mocks {empire} cuisine, again",
  "Visa fees waived between {empire} and {empire2} for {n} cycles",
  "Cruise stranded near {system} after captain forgets fuel; passengers patient",
  "Resort on {planet} closes for renovations, customers asked to bring patience",
  "{port} transit guide now in {n2} languages, none of them spoken by tourists",
  "Backpacker association on {planet} releases tip sheet, mostly about boots",
  "{empire} tour guides unionize, demand {percent}% pay raise and respect",
  "Eco-resort on {planet} rebrands as 'less eco-resort' after audit",
  "Public beach on {port} expanded by {percent}%, sea grumbles politely",
  "Travel insurance claims spike after {commodity} festival on {planet}",
  "Sky lift on {planet} stuck mid-cycle, tourists view ad-supported sunset",
  "{empire} coast guard rescues {n2} from {commodity} festival flotilla",
  "Tourist train through {sector} adds dining car, dining car adds prices",
  "Honeymoon package on {planet} includes {n} sunsets, two suns",
  "{port} airport adds robot bartenders, queue paradoxically longer",
  "Tour group reports being charmed by {planet} customs officer's small talk",
  "Stargazing pad on {planet} listed as 'best place to feel small', exceeds expectations",
];

// ── 16. Fashion & Trends ───────────────────────────────────────
const FASHION: string[] = [
  "Anti-grav heels make comeback on {port} runway week",
  "{empire} fashion editor declares {commodity} the new black, again",
  "{ceo}'s clothing line draws ridicule then sells out in {n} hours",
  "{port} runway show features {adj} biofiber jackets, audience applauds politely",
  "{empire} influencer endorses {commodity} skin treatment, dermatologists groan",
  "Vintage {commodity} jewelry surges in resale, prices up {percent}%",
  "Hoverboot rental services launch on {planet}, ankles relieved",
  "{empire} fashion police actually exist now, fine for poor color coordination",
  "Couture house on {port} debuts collection inspired by {empire2} graveyard art",
  "{ceo} wears same outfit twice, internet briefly malfunctions",
  "{empire} dress code permits casual Friday on Wednesdays now",
  "{commodity} sneakers reissue; collectors line up for {n2} cycles",
  "{planet} street style trend: shoulder pads big enough to land craft on",
  "Wedding dress made of recycled {commodity} ends up on permanent display",
  "Tailor {ceo} sued by {ceo2} over identical capes, settles in cape",
  "{empire} style guide updates after {n2}-cycle hiatus; lapels now legal again",
  "Hatmaker on {planet} debuts hat that doubles as comm device, fall risk noted",
  "{empire} fashion week pushed back {n} cycles after delivery of fabric was lost",
  "Knit jumper trend returns; analysts cite {percent}% rise in 'cozy economy'",
  "{ceo} sells personal wardrobe at auction, raises {credits} for charity",
  "Designer on {planet} apologizes for collection 'mocking gravity'",
  "{commodity} accessory of the cycle: ear-cuff that hums {empire} anthems",
  "Eyewear brand on {port} introduces specs that judge readers softly",
  "{port} streetwear collective declares jeans dead; jeans hold press conference",
  "{empire} ambassador's silk gown praised; {empire2} declares it 'too silky'",
];

// ── 17. Education & Academia ───────────────────────────────────
const ACADEMIA: string[] = [
  "{empire} University paper retracted over fabricated stardata",
  "Galactic ranking puts {empire} top in physics, last in cafeteria food",
  "{port} library acquires {n2} ancient {commodity} scrolls, smell included",
  "Student loans on {planet} now expressed in {commodity}; nobody happy",
  "{empire} professor {ceo} tenured after {n2} cycles, briefly considered leaving anyway",
  "Gap-cycle programs to {planet} surge {percent}% as parents quietly relieved",
  "Academic strike at {empire} system halts research and complaints",
  "{empire} school board approves {commodity} unit; parents petition for less {commodity}",
  "Online course in 'How to Pay Attention' from {planet} institute reaches {n2}M",
  "{ceo}'s honorary doctorate from {empire} university revoked, then awarded again",
  "Spelling bee on {planet} won by AI; medal handed back politely",
  "{empire} university launches debate on whether debate is necessary",
  "Conference on {commodity} draws {percent}% more attendees than presenters",
  "{empire} institute closes department of common sense for budget reasons",
  "Galactic dictionary adds {n2} new words including 'hyperflug' and 'meh'",
  "Student protest at {planet} campus achieves cafeteria reform, world peace tabled",
  "Researcher publishes paper proving paper publishing harms research",
  "{empire} archive digitizes oldest known invoice; still unpaid",
  "{port} school district flips schedule by {percent}% to test theory",
  "Galactic spelling bee finalist eliminated on the word 'finalist'",
  "{empire} education ministry reduces homework by decree, productivity up {percent}%",
  "Robotics fair on {planet} ends in {n} runaway robots; one elected to council",
  "{empire} academy adds {commodity} studies; lab coats not yet stained",
  "{port} chess team disqualified for {percent}% telepathy",
  "Citation index of {ceo} climbs {percent}%, mostly self-citations",
];

// ── 18. Xenobiology ────────────────────────────────────────────
const XENOBIOLOGY: string[] = [
  "Researchers describe new sentient mold on {planet}",
  "{empire} survey logs {n2} new microorganisms in {sector} dust clouds",
  "Mating call of {planet} cave eel decoded; mostly indignation",
  "Conservation effort on {planet} saves {percent}% of last vine snake population",
  "Newly observed {planet} fungus glows in time with the local pulsar",
  "{empire} biologist {ceo} reports moth population recovering on {port}",
  "Translation device for {planet} herd beasts works {percent}% of the time",
  "Endangered list adds {n2} species after {empire} habitat survey",
  "Aquatic life on {planet} found to follow regular meeting schedule",
  "Rogue genetic experiment on {planet} produces friendly hybrid; adopted by lab",
  "{empire} zoo welcomes new {adj} pup, names contest open",
  "Migratory route of {planet} sky whales redirected by {percent}%, theories abound",
  "Insectoid hive on {planet} grants visiting researchers honorary worker status",
  "{empire} botanists isolate {commodity} from {planet} lichens, smells like home",
  "Apex predator on {planet} discovered to be photosynthetic, ecologists shrug",
  "Wildlife corridor through {sector} approved over {empire} agriculture's protests",
  "{port} researchers attach trackers to {n2} sentient slimes; slimes ambivalent",
  "Scientists confirm {planet} eel can pun in three languages",
  "{empire} agency confirms {planet} sky-snail is not, in fact, a meteor",
  "Migration pattern of {planet} song-bats includes {n}-cycle harmonic jam session",
  "Researcher claims {planet} sentient kelp filed grievance with HR",
  "{empire} releases breeding plan for endangered {adj} mammal on {port}",
  "Pet trade on {planet} cracks down on illegal {commodity} ferrets",
  "Marine biologists on {planet} reclassify squid as 'committee'",
  "{ceo}'s pet sentient palm signs autograph, prints sold for {credits}",
];

// ── 19. Obituaries & Tributes ──────────────────────────────────
const OBITUARY: string[] = [
  "Industrialist {ceo} eulogized as 'tireless and largely tolerable'",
  "{empire} statesman {ceo} dies at {n2}, leaves library of {n2}M scrolls",
  "Veteran captain {ceo} of the {company} freight fleet passes after {n2} cycles aloft",
  "Memorial service for {ceo} held at {planet}; attendance overflowed orbit",
  "{empire} cultural figure {ceo} remembered for 'singular, occasional' charm",
  "Professor emeritus {ceo} of {planet} institute dies; chair to be retired",
  "{ceo} pioneer of {commodity} engineering, passes; legacy {n2} patents",
  "Journalist {ceo} known for asking inconvenient questions has died",
  "Composer {ceo}'s final symphony premiered posthumously in {empire} hall",
  "{empire} founding member {ceo} eulogized as 'a complicated old hand'",
  "Athlete {ceo} retired hero, championships {n}, anecdotes uncountable",
  "{ceo} explorer first to map {sector} fringe, has died at {n2}",
  "{empire} ambassador {ceo}, who once thrown shoe at podium, dies at {n2}",
  "Ex-board member of {company} {ceo} passes; obit lists {n2} affiliations",
  "{ceo}, sentient kelp activist, mourned by {percent}% of relevant ecosystems",
  "{empire} actor {ceo}'s farewell tour cut short; tour bus signs petition",
  "{ceo} who patented the breakfast sandwich licenses one final smile",
  "{empire} chess grandmaster {ceo} defeats death after {n2} delays",
  "Engineer {ceo} of the original {planet} mag-rail, has passed",
  "Author of 'Quiet Years on {planet}' has quietly stepped behind the curtain",
  "{ceo}, longtime mayor of {port}, leaves council bench in mourning",
  "{empire} general {ceo}, who once misplaced a fleet, dies at {n2}",
  "{ceo} of {company}'s legendary marketing run laid to rest with last billboard",
  "Holovid critic {ceo} dies; final review described life as 'three stars, one moon'",
  "{empire} historian {ceo}, encyclopedic in life, indexed in death",
];

// ── 20. Sci-Fi Homages ─────────────────────────────────────────
const HOMAGE: string[] = [
  // Hitchhiker's
  "Towel sales up {percent}% on {planet} ahead of Galactic Hitchhiker's Day",
  "Survey finds {percent}% of {empire} citizens consider their planet 'mostly harmless'",
  "{port} authorities remind travelers that, statistically, the answer is 42",
  "Improbability drive prices fluctuated wildly today; analysts blame finite probability",
  "Vogon Constructor Fleet detected near {system}; locals advised to ignore poetry recitals",
  "{company} debuts in-flight beverage 'almost, but not quite, entirely unlike tea'",
  "Babel fish supply rationed on {port} after translator union strike",
  "{ceo} described as 'about as inconspicuous as a brick at a glass convention'",
  // Asimov
  "Psychohistorical model predicts {percent}% chance of {empire} collapse within {n2} centuries",
  "Three Laws Robotics violation reported on {planet}; investigation pending",
  "{empire} Foundation conference debates Seldon Plan revisions over snacks",
  "Mule sighting on {sector} fringe ruled 'almost certainly unrelated'",
  // Dune
  "{commodity} flow disrupted on {planet}; trade guilds concerned",
  "Spice mélange futures trading suspended on {sector} exchange",
  "Sandworm advisory issued for {planet} dunes, again",
  "{empire} herald repeats: he who controls the {commodity} controls the universe",
  // Star Trek
  "Sensors detect unusual readings near {planet}; scientists puzzled",
  "{empire} Prime Directive review committee adjourned indefinitely",
  "Holodeck malfunction on {planet} resolved by reading actual book",
  "Tribble outbreak quarantined on {port}; furry quotient up {percent}%",
  // Star Wars
  "{ceo} dismisses rumors of 'ancient religion' as 'a hokey old myth'",
  "{empire} senate approves emergency powers for {n} cycles, definitely temporarily",
  "Smuggler {ceo} insists Kessel-equivalent run completed in {n} parsecs",
  // Blade Runner
  "{planet} weather forecast: continuous rain. Again",
  "{company} replicant program suspended pending {n2}-question test review",
  "Origami unicorn left at scene of {ceo}'s farewell speech",
  // Alien
  "{company} promises this time the cargo hold is, quote, 'definitely empty'",
  "Hygiene inspectors leaving {planet} bay {n2} early; nobody asked why",
  // Firefly
  "{ceo} insists their cargo is 'just legitimate goods, shiny'",
  "{port} preacher on {planet} reminds congregation: cannot stop the signal",
  // 2001
  "{company} AI module reports it 'cannot do that' for {n} cycles running",
  "Monolith detected near {planet} moon; tourism board orders gift shop",
  // Misc
  "{empire} probe inscribed with greeting in {n2} languages, including snark",
  "Improbable encounter at {port} bar: same captain, three timelines",
  "{ceo} reportedly 'long, dead, and slightly cross about it' after fan event",
  "Galactic survey of meanings of life narrows answer to '42, possibly tea'",
];

// ── Registry ──────────────────────────────────────────────────
const TEMPLATE_POOLS: Record<TickerCategory, string[]> = {
  // Structural categories empty here — sourced live by tickerFeed.ts.
  headline: [],
  leader: [],
  stock: [],

  politics: POLITICS,
  corporate: CORPORATE,
  market_mover: MARKET_MOVER,
  crime: CRIME,
  science: SCIENCE,
  sports: SPORTS,
  celebrity: CELEBRITY,
  cosmic_weather: COSMIC_WEATHER,
  local: LOCAL,
  health: HEALTH,
  religion: RELIGION,
  blotter: BLOTTER,
  food: FOOD,
  realestate: REALESTATE,
  travel: TRAVEL,
  fashion: FASHION,
  academia: ACADEMIA,
  xenobiology: XENOBIOLOGY,
  obituary: OBITUARY,
  homage: HOMAGE,
};

/** Flat list of every flavor template, useful for tests and counts. */
export const ALL_FLAVOR_TEMPLATES: FlavorTemplate[] = FLAVOR_CATEGORIES.flatMap(
  (cat) =>
    (TEMPLATE_POOLS[cat] ?? []).map<FlavorTemplate>((t) => ({
      category: cat,
      template: t,
    })),
);

/** Templates for one category, in declaration order. */
export function getTemplatesForCategory(cat: TickerCategory): FlavorTemplate[] {
  return (TEMPLATE_POOLS[cat] ?? []).map<FlavorTemplate>((t) => ({
    category: cat,
    template: t,
  }));
}

/** Total templates across all twenty flavor pools. */
export function totalFlavorTemplateCount(): number {
  return ALL_FLAVOR_TEMPLATES.length;
}
